# Generated by Django 6.0.5 on 2026-05-23 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('delivery_method', models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('ukrposhta', 'Укрпошта'), ('courier', 'Кур’єр по місту'), ('pickup', 'Самовивіз')], default='nova_poshta', max_length=20, verbose_name='Спосіб доставки')),
                ('address', models.CharField(max_length=300, verbose_name='Адреса / відділення')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('has_prescription', models.BooleanField(default=False, verbose_name='Наявний рецепт')),
                ('prescription_note', models.TextField(blank=True, verbose_name='Примітка щодо рецепту')),
                ('status', models.CharField(choices=[('pending', 'В обробці'), ('confirmed', 'Підтверджено'), ('shipping', 'Доставляється'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Загальна сума')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Симптом')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Симптом',
                'verbose_name_plural': 'Симптоми',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Виробник')),
                ('description', models.TextField(verbose_name='Опис')),
                ('composition', models.TextField(blank=True, verbose_name='Склад')),
                ('dosage', models.CharField(blank=True, max_length=200, verbose_name='Дозування')),
                ('contraindications', models.TextField(blank=True, verbose_name='Протипоказання')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (грн)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Залишок на складі')),
                ('is_prescription', models.BooleanField(default=False, verbose_name='Рецептурний препарат')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступний')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='shop.category', verbose_name='Категорія')),
                ('symptoms', models.ManyToManyField(blank=True, related_name='medicines', to='shop.symptom', verbose_name='Симптоми')),
            ],
            options={
                'verbose_name': 'Ліки',
                'verbose_name_plural': 'Ліки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.medicine', verbose_name='Ліки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
    ]
